using System;
using System.Collections.Generic;

namespace VersionManagementSystem.Core.Entities {
    /// <summary>
    /// A registered target application (e.g. Felys Jewelry System, BenPOS System).
    /// The system supports any number of applications — nothing is hard-coded.
    /// </summary>
    public class Application {
        // Identity is generated by the database (identity column), never in this class.
        public int ApplicationId { get; set; }

        public string ApplicationCode { get; set; } = string.Empty;

        public string ApplicationName { get; set; } = string.Empty;

        public string? Description { get; set; }

        public bool IsActive { get; set; } = true;

        public DateTime CreatedDate { get; set; }

        public ICollection<ApplicationVersion> Versions { get; set; } = new List<ApplicationVersion>();
    }
}
