using System;
using System.Collections.Generic;
using VersionManagementSystem.Core.Enums;

namespace VersionManagementSystem.Core.Entities {
    /// <summary>
    /// A single version record for an application.
    /// Update packages, channels and publishing metadata (Phases 2-3) build on top of this.
    /// </summary>
    public class ApplicationVersion {
        // Identity is generated by the database (identity column), never in this class.
        public int ApplicationVersionId { get; set; }

        public int ApplicationId { get; set; }

        public Application? Application { get; set; }

        // Stored as separate components so version comparison never relies on string parsing at query time.
        public int Major { get; set; }
        public int Minor { get; set; }
        public int Patch { get; set; }
        public int Revision { get; set; }

        public ReleaseType ReleaseType { get; set; }

        public ReleaseStatus ReleaseStatus { get; set; } = ReleaseStatus.Draft;

        public DateTime ReleaseDate { get; set; }

        public string? ReleaseNotes { get; set; }

        public string? MinimumSupportedVersion { get; set; }

        public bool IsMandatory { get; set; }

        public UpdateChannel Channel { get; set; } = UpdateChannel.Stable;

        public DateTime CreatedDate { get; set; }

        public string? CreatedBy { get; set; }

        public DateTime? PublishedDate { get; set; }

        public string? PublishedBy { get; set; }

        public string VersionString => new Version(Major, Minor, Patch, Revision).ToString(4);

        public ICollection<ReleaseNote> StructuredReleaseNotes { get; set; } = new List<ReleaseNote>();

        public ICollection<UpdatePackage> Packages { get; set; } = new List<UpdatePackage>();
    }
}
