using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VersionManagementSystem.Core.Entities {
    /// <summary>
    /// One row per (Application, MachineName) — the last version we know that
    /// machine to be running, and when it last checked in / last updated.
    /// </summary>
    public class ClientInstallation {
        // Identity is generated by the database (identity column), never in this class.
        public int ClientInstallationId { get; set; }

        public int ApplicationId { get; set; }

        public Application? Application { get; set; }

        public string MachineName { get; set; } = string.Empty;

        public string CurrentVersion { get; set; } = string.Empty;

        public DateTime LastChecked { get; set; }

        public DateTime? LastUpdated { get; set; }
    }
}
