using System;
using VersionManagementSystem.Core.Enums;

namespace VersionManagementSystem.Core.Entities {
    /// <summary>
    /// A single structured release note line item (e.g. one "New Feature" bullet)
    /// belonging to an ApplicationVersion. Complements the free-text summary already
    /// stored on ApplicationVersion.ReleaseNotes.
    /// </summary>
    public class ReleaseNote {
        // Identity is generated by the database (identity column), never in this class.
        public int ReleaseNoteId { get; set; }

        public int ApplicationVersionId { get; set; }

        public ApplicationVersion? ApplicationVersion { get; set; }

        public ReleaseNoteCategory Category { get; set; }

        public string Description { get; set; } = string.Empty;

        public int SortOrder { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}
