using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VersionManagementSystem.Core.Entities {
    public class UpdateHistory {

        // Identity is generated by the database (identity column), never in this class.
        public int UpdateHistoryId { get; set; }

        public int ApplicationId { get; set; }

        public Application? Application { get; set; }

        public string FromVersion { get; set; } = string.Empty;

        public string ToVersion { get; set; } = string.Empty;

        public DateTime UpdateDate { get; set; }

        /// <summary>Free-text outcome reported by the client updater, e.g. "Success", "Failed", "RolledBack".</summary>
        public string Status { get; set; } = string.Empty;

        public string MachineName { get; set; } = string.Empty;
    }
}
