using System;
using VersionManagementSystem.Core.Enums;

namespace VersionManagementSystem.Core.Entities {
    /// <summary>
    /// Metadata for a single uploaded package file (zip/exe/msi) tied to a version.
    /// A version can have more than one package (e.g. a zip AND an msi), but only
    /// one package per PackageType per version.
    /// </summary>
    public class UpdatePackage {
        // Identity is generated by the database (identity column), never in this class.
        public int UpdatePackageId { get; set; }

        public int ApplicationVersionId { get; set; }

        public ApplicationVersion? ApplicationVersion { get; set; }

        public string FileName { get; set; } = string.Empty;

        // Path is relative to the configured storage root — never a raw absolute
        // filesystem path is accepted from, or returned to, an API client.
        public string FilePath { get; set; } = string.Empty;

        public long FileSize { get; set; }

        public string Checksum { get; set; } = string.Empty;

        public PackageType PackageType { get; set; }

        public DateTime CreatedDate { get; set; }

        public string? UploadedBy { get; set; }
    }
}
